spring:
  application:
    name: comic-one-client
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
server:
  port: 8600
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
 